In [1]:
import pandas as pd
import os
from sqlalchemy import create_engine, inspect
import logging
import time

In [40]:
from sqlalchemy import create_engine,text

In [26]:
# Set up MySQL connection details
username = 'root'
password = 'Raisha789'
host = 'localhost'
port = 3306
database = 'superstor_db'

In [64]:
# Create SQLAlchemy engine for MySQL connection
engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

In [65]:
conn = engine.connect()

In [5]:
tables_df = pd.read_sql("SHOW TABLES", conn)
print(tables_df )

  Tables_in_superstor_db
0        superstore_data

In [6]:
df = pd.read_sql("Select * from superstore_data",conn)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9694 entries, 0 to 9693
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9694 non-null   int64
 1   Order ID       9694 non-null   object
 2   Order Date     9694 non-null   object
 3   Ship Date      9694 non-null   object
 4   Ship Mode      9694 non-null   object
 5   Customer ID    9694 non-null   object
 6   Customer Name  9694 non-null   object
 7   Segment        9694 non-null   object
 8   Country        9694 non-null   object
 9   City           9694 non-null   object
 10  State          9694 non-null   object
 11  Postal Code    9694 non-null   int64
 12  Region         9694 non-null   object
 13  Product ID     9694 non-null   object
 14  Category       9694 non-null   object
 15  Sub-Category   9694 non-null   object
 16  Product Name   9694 non-null   object
 17  Sales          9694 non-null   float64
 18  Quantity       9694 non-null   int64
 19  Discount       9694 non-null   float64
 20  Profit         9694 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [8]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2016-138688,06/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [9]:
df.columns = df.columns.str.lower()

In [10]:
df = df.apply(lambda x: x.str.lower() if x.dtype == "object" else x)

In [11]:
df.head(3)

,row id,order id,order date,ship date,ship mode,customer id,customer name,segment,country,city,...,postal code,region,product id,category,sub-category,product name,sales,quantity,discount,profit
0,1,ca-2016-152156,11/08/2016,11/11/2016,second class,cg-12520,claire gute,consumer,united states,henderson,...,42420,south,fur-bo-10001798,furniture,bookcases,bush somerset collection bookcase,261.96,2,0.0,41.9136
1,2,ca-2016-152156,11/08/2016,11/11/2016,second class,cg-12520,claire gute,consumer,united states,henderson,...,42420,south,fur-ch-10000454,furniture,chairs,"hon deluxe fabric upholstered stacking chairs,...",731.94,3,0.0,219.5820
2,3,ca-2016-138688,06/12/2016,6/16/2016,second class,dv-13045,darrin van huff,corporate,united states,los angeles,...,90036,west,off-la-10000240,office supplies,labels,self-adhesive address labels for typewriters b...,14.62,2,0.0,6.8714

In [12]:
#converting objectype to date type of all the column 

df['order date'] = pd.to_datetime(df['order date'])
df['ship date'] = pd.to_datetime(df['ship date'])

In [13]:
# replacing space with _ for convinence 
df = df.rename(columns={
    'row id': 'row_id',
    'order id': 'order_id',
    'order date': 'order_date',
    'ship date': 'ship_date',
    'ship mode': 'ship_mode',
    'customer id': 'customer_id',
    'customer name': 'customer_name',
    'postal code': 'postal_code',
    'product id': 'product_id',
    'sub-category': 'sub_category',
    'product name': 'product_name'
})

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9694 entries, 0 to 9693
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9694 non-null   int64
 1   order_id       9694 non-null   object
 2   order_date     9694 non-null   datetime64[ns]
 3   ship_date      9694 non-null   datetime64[ns]
 4   ship_mode      9694 non-null   object
 5   customer_id    9694 non-null   object
 6   customer_name  9694 non-null   object
 7   segment        9694 non-null   object
 8   country        9694 non-null   object
 9   city           9694 non-null   object
 10  state          9694 non-null   object
 11  postal_code    9694 non-null   int64
 12  region         9694 non-null   object
 13  product_id     9694 non-null   object
 14  category       9694 non-null   object
 15  sub_category   9694 non-null   object
 16  product_name   9694 non-null   object
 17  sales          9694 non-null   float64
 18  quantity       9694 non-null   int64
 19  discount       9694 non-null   float64
 20  profit         9694 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [15]:
df.columns = df.columns.str.strip()

In [16]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,ca-2016-152156,2016-11-08,2016-11-11,second class,cg-12520,claire gute,consumer,united states,henderson,...,42420,south,fur-bo-10001798,furniture,bookcases,bush somerset collection bookcase,261.9600,2,0.00,41.9136
1,2,ca-2016-152156,2016-11-08,2016-11-11,second class,cg-12520,claire gute,consumer,united states,henderson,...,42420,south,fur-ch-10000454,furniture,chairs,"hon deluxe fabric upholstered stacking chairs,...",731.9400,3,0.00,219.5820
2,3,ca-2016-138688,2016-06-12,2016-06-16,second class,dv-13045,darrin van huff,corporate,united states,los angeles,...,90036,west,off-la-10000240,office supplies,labels,self-adhesive address labels for typewriters b...,14.6200,2,0.00,6.8714
3,4,us-2015-108966,2015-10-11,2015-10-18,standard class,so-20335,sean o'donnell,consumer,united states,fort lauderdale,...,33311,south,fur-ta-10000577,furniture,tables,bretford cr4500 series slim rectangular table,957.5775,5,0.45,-383.0310
4,5,us-2015-108966,2015-10-11,2015-10-18,standard class,so-20335,sean o'donnell,consumer,united states,fort lauderdale,...,33311,south,off-st-10000760,office supplies,storage,eldon fold 'n roll cart system,22.3680,2,0.20,2.5164

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.duplicated(subset =['customer_id','customer_name','segment',
                   'country','city','state',
                   'postal_code','region']).sum()

np.int64(4859)

In [19]:
df.duplicated(subset =('product_id','category',
                  'sub_category','product_name')).sum()

np.int64(7852)

In [20]:
df.drop('row_id', axis=1)

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,ca-2016-152156,2016-11-08,2016-11-11,second class,cg-12520,claire gute,consumer,united states,henderson,kentucky,42420,south,fur-bo-10001798,furniture,bookcases,bush somerset collection bookcase,261.9600,2,0.00,41.9136
1,ca-2016-152156,2016-11-08,2016-11-11,second class,cg-12520,claire gute,consumer,united states,henderson,kentucky,42420,south,fur-ch-10000454,furniture,chairs,"hon deluxe fabric upholstered stacking chairs,...",731.9400,3,0.00,219.5820
2,ca-2016-138688,2016-06-12,2016-06-16,second class,dv-13045,darrin van huff,corporate,united states,los angeles,california,90036,west,off-la-10000240,office supplies,labels,self-adhesive address labels for typewriters b...,14.6200,2,0.00,6.8714
3,us-2015-108966,2015-10-11,2015-10-18,standard class,so-20335,sean o'donnell,consumer,united states,fort lauderdale,florida,33311,south,fur-ta-10000577,furniture,tables,bretford cr4500 series slim rectangular table,957.5775,5,0.45,-383.0310
4,us-2015-108966,2015-10-11,2015-10-18,standard class,so-20335,sean o'donnell,consumer,united states,fort lauderdale,florida,33311,south,off-st-10000760,office supplies,storage,eldon fold 'n roll cart system,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9689,ca-2014-110422,2014-01-21,2014-01-23,second class,tb-21400,tom boeckenhauer,consumer,united states,miami,florida,33180,south,fur-fu-10001889,furniture,furnishings,ultra door pull handle,25.2480,3,0.20,4.1028
9690,ca-2017-121258,2017-02-26,2017-03-03,standard class,db-13060,dave brooks,consumer,united states,costa mesa,california,92627,west,fur-fu-10000747,furniture,furnishings,tenex b1-re series chair mats for low pile car...,91.9600,2,0.00,15.6332
9691,ca-2017-121258,2017-02-26,2017-03-03,standard class,db-13060,dave brooks,consumer,united states,costa mesa,california,92627,west,tec-ph-10003645,technology,phones,aastra 57i voip phone,258.5760,2,0.20,19.3932
9692,ca-2017-121258,2017-02-26,2017-03-03,standard class,db-13060,dave brooks,consumer,united states,costa mesa,california,92627,west,off-pa-10004041,office supplies,paper,"it's hot message books with stickers, 2 3/4"" x...",29.6000,4,0.00,13.3200
9693,ca-2017-119914,2017-05-04,2017-05-09,second class,cc-12220,chris cortes,consumer,united states,westminster,california,92683,west,off-ap-10002684,office supplies,appliances,"acco 7-outlet masterpiece power center, wihtou...",243.1600,2,0.00,72.9480

In [21]:
#cleanes table storing in mysql
df.to_sql('cleaned_raw_data', con=engine, if_exists='replace', index=False)

9694

In [22]:
conn.close()

In [29]:
pd.read_sql("Select * from cleaned_raw_data",conn)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,ca-2016-152156,2016-11-08,2016-11-11,second class,cg-12520,claire gute,consumer,united states,henderson,...,42420,south,fur-bo-10001798,furniture,bookcases,bush somerset collection bookcase,261.9600,2,0.00,41.9136
1,2,ca-2016-152156,2016-11-08,2016-11-11,second class,cg-12520,claire gute,consumer,united states,henderson,...,42420,south,fur-ch-10000454,furniture,chairs,"hon deluxe fabric upholstered stacking chairs,...",731.9400,3,0.00,219.5820
2,3,ca-2016-138688,2016-06-12,2016-06-16,second class,dv-13045,darrin van huff,corporate,united states,los angeles,...,90036,west,off-la-10000240,office supplies,labels,self-adhesive address labels for typewriters b...,14.6200,2,0.00,6.8714
3,4,us-2015-108966,2015-10-11,2015-10-18,standard class,so-20335,sean o'donnell,consumer,united states,fort lauderdale,...,33311,south,fur-ta-10000577,furniture,tables,bretford cr4500 series slim rectangular table,957.5775,5,0.45,-383.0310
4,5,us-2015-108966,2015-10-11,2015-10-18,standard class,so-20335,sean o'donnell,consumer,united states,fort lauderdale,...,33311,south,off-st-10000760,office supplies,storage,eldon fold 'n roll cart system,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9689,9990,ca-2014-110422,2014-01-21,2014-01-23,second class,tb-21400,tom boeckenhauer,consumer,united states,miami,...,33180,south,fur-fu-10001889,furniture,furnishings,ultra door pull handle,25.2480,3,0.20,4.1028
9690,9991,ca-2017-121258,2017-02-26,2017-03-03,standard class,db-13060,dave brooks,consumer,united states,costa mesa,...,92627,west,fur-fu-10000747,furniture,furnishings,tenex b1-re series chair mats for low pile car...,91.9600,2,0.00,15.6332
9691,9992,ca-2017-121258,2017-02-26,2017-03-03,standard class,db-13060,dave brooks,consumer,united states,costa mesa,...,92627,west,tec-ph-10003645,technology,phones,aastra 57i voip phone,258.5760,2,0.20,19.3932
9692,9993,ca-2017-121258,2017-02-26,2017-03-03,standard class,db-13060,dave brooks,consumer,united states,costa mesa,...,92627,west,off-pa-10004041,office supplies,paper,"it's hot message books with stickers, 2 3/4"" x...",29.6000,4,0.00,13.3200
9693,9994,ca-2017-119914,2017-05-04,2017-05-09,second class,cc-12220,chris cortes,consumer,united states,westminster,...,92683,west,off-ap-10002684,office supplies,appliances,"acco 7-outlet masterpiece power center, wihtou...",243.1600,2,0.00,72.9480

### Creating star schema for better exploration

In [41]:
# 1.Created Fact table AS sales_fact
create_table_query = """
CREATE TABLE IF NOT EXISTS sales_fact (
    order_id VARCHAR(50),
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR(50),
    customer_id VARCHAR(50),
    product_id VARCHAR(50),
    sales DECIMAL(10,2),
    quantity INT,
    discount FLOAT,
    profit FLOAT
);
"""

insert_data_query = """
INSERT INTO sales_fact (order_id, order_date, ship_date, ship_mode, customer_id, product_id, sales, quantity, discount, profit)
SELECT 
    order_id, 
    order_date, 
    ship_date, 
    ship_mode, 
    customer_id, 
    product_id, 
    sales, 
    quantity, 
    discount, 
    profit 
FROM cleaned_raw_data;
"""

# 3. Execute the commands
with engine.connect() as conn:
    conn.execute(text(create_table_query))
    print("Table 'sales_fact' created or already exists.")
    
    conn.execute(text(insert_data_query))
    conn.commit()  
    print("Data successfully loaded into 'sales_fact'.")

Table 'sales_fact' created or already exists.
Data successfully loaded into 'sales_fact'.

In [57]:
# 2.Created dimensional table as customer_dim
query_customer = """
CREATE TABLE IF NOT EXISTS customer_dim (
    customer_id VARCHAR(50),
    customer_name VARCHAR(100),
    segment VARCHAR(50),
    country VARCHAR(50),
    city VARCHAR(50),
    state VARCHAR(50),
    postal_code INT,
    region VARCHAR(50)
);
"""


insert_customer = """
INSERT INTO customer_dim
SELECT DISTINCT
    customer_id,
    customer_name,
    segment,
    country,
    city,
    state,
    postal_code,
    region
FROM cleaned_raw_data;

"""

In [59]:
with engine.connect() as conn:
    conn.execute(text(query_customer))
    conn.execute(text(insert_customer))
    conn.commit()

In [67]:
# 3.Created dimensional table as product_dim
query_product = """
CREATE TABLE IF NOT EXISTS  product_dim (
    product_id VARCHAR(50),
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_name TEXT
);
"""

insert_product = """
INSERT INTO product_dim
SELECT DISTINCT
    product_id,
    category,
    sub_category,
    product_name
FROM cleaned_raw_data;
"""

In [68]:
with engine.connect() as conn:
    conn.execute(text(query_product))
    conn.execute(text(insert_product))
    conn.commit()

##### In this notebook, a connection engine was created between MySQL and Jupyter Notebook. The raw table was cleaned and transformed into a star schema by creating fact and dimension tables. The next steps involve data exploration, insight generation, and predictive analysis using machine learning techniques.

In [ ]:
#